server:
  port: ${PORT:8080}
spring:
  application:
    name: email-notification-service

  rabbitmq:
    addresses: ${RABBITMQ_URL}

#  mail:
#
#    host: smtp.gmail.com
#
#    port: 465
#
#    username: ${MAIL_USERNAME}
#
#    password: ${MAIL_PASSWORD}
#
#    properties:
#        mail.smtp.auth: true
#        mail.smtp.starttls.enable: true
##        mail.smtp.starttls.required: true
#        mail.smtp.connectiontimeout: 10000
#        mail.smtp.timeout: 10000
#        mail.smtp.writetimeout: 10000
resend:
  api-key: ${RESEND_API_KEY}
  from: ${MAIL_USERNAME}